// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function SubmitInput(arg1) {
  return window['go']['main']['App']['SubmitInput'](arg1);
}
