// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSavedLaunchOptions():Promise<main.LaunchOptions>;

export function HideWindow():Promise<void>;

export function IsRunning():Promise<boolean>;

export function OpenEIP():Promise<void>;

export function Quit():Promise<void>;

export function ResumePendingConnect():Promise<boolean>;

export function SaveLaunchOptions(arg1:main.LaunchOptions):Promise<void>;

export function ShowWindow():Promise<void>;

export function Start(arg1:main.LaunchOptions):Promise<void>;

export function Stop():Promise<void>;

export function SubmitInput(arg1:string):Promise<void>;
