// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type LaunchOptions = {
  protocol?: string;
  server?: string;
  port: number;
  username: string;
  password: string;
  socksBind: string;
  httpBind: string;
  secondaryDnsServer?: string;
  authType?: string;
  loginDomain?: string;
  clientDataFile?: string;
  tunMode: boolean;
  debugDump: boolean;
};

export function HideWindow():Promise<void>;

export function GetSavedLaunchOptions():Promise<LaunchOptions>;

export function IsRunning():Promise<boolean>;

export function Quit():Promise<void>;

export function ResumePendingConnect():Promise<boolean>;

export function ShowWindow():Promise<void>;

export function SaveLaunchOptions(arg1:LaunchOptions):Promise<void>;

export function Start(arg1:LaunchOptions):Promise<void>;

export function Stop():Promise<void>;

export function SubmitInput(arg1:string):Promise<void>;
